[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.44.0", features = ["full"] }
tower = "0.5.2"

[dev-dependencies]
anyhow = "1.0.97"
httpc-test = "0.1.10"
